In [ ]:
#1.
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#2.
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [ ]:
#3.
import numpy as np
arr=np.eye(3,3)
print(arr)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#4.
import numpy as np
a=np.random.randint(0,1,10)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#5.
import numpy as np
a =np.zeros(10)
b =np.ones(10)
print(a)
print(b)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#6.
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr[2])

30


In [1]:
#7.
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,1,2,3],[5,6,7,8]])
print(a)

print(a[1,2])

[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [5 6 7 8]]
7


In [ ]:
#8.
import numpy as np
a=np.array([5,10,15,20,25])
print(a[-1])

25


In [3]:
#9.
import numpy as np
a=np.array([1,3,5,7,9,11])
selected_elements =a[[1,3,4]]
print(selected_elements)
print(a[1])
print(a[3])
print(a[4])

[3 7 9]
3
7
9


In [ ]:
#10.
import numpy as np
a=np.array([[[1,2,3],[4,5,6]],
             [[7,8,9],[1,2,3]],
             [[1,2,3],[4,5,6]]])

print(a)

print(a[1,1,1])

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]

 [[1 2 3]
  [4 5 6]]]
2


In [10]:
#11.
import numpy as np
a=np.array([2,4,6,8,10,12])
print(a[:3])


[2 4 6]


In [12]:
#12.
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12],
            [1,2,3,4]])
print(a[:2,-2:])


[[3 4]
 [7 8]]


In [15]:
#13.
import numpy as np
a=np.array([0,1,2,3,4,5,6,7,8,9])
print(a[0:-1:2])
print(a[::2])

[0 2 4 6 8]
[0 2 4 6 8]


In [16]:
#14.
import numpy as np
a=np.array([[1,2,3,4],
            [5,6,7,8],
            [9,10,11,12]])
print(a[:,-2:])


[[ 3  4]
 [ 7  8]
 [11 12]]


In [17]:
#15.
import numpy as np
a=np.array([[1,2,3,4,5],
            [5,6,7,8,5],
            [9,10,11,12,13],
            [1,2,3,4,5],
            [6,7,8,9,0]])
print(a[1:4,1:4])

[[ 6  7  8]
 [10 11 12]
 [ 2  3  4]]


In [22]:
#16.
import numpy as  np
int_array= np.arange(6)
float_array=int_array.astype(float)
print(float_array)

[0. 1. 2. 3. 4. 5.]


In [18]:
#17.
import numpy as np
a=np.array([[1,0,1],
            [1,1,0],
            [0,1,0]])
print(a.astype(bool))

[[ True False  True]
 [ True  True False]
 [False  True False]]


In [25]:
#18.
complex_array=np.array([1+2j,3+4j,5+6j])
print(complex_array)

[1.+2.j 3.+4.j 5.+6.j]


In [27]:
#19
a=np.array(["1","2","3"])
b=a.astype(int)
print(b)

[1 2 3]


In [28]:
#20.
import numpy as np

a=np.array([3.45,2.1,6.7,8.9])
b=a.astype('i')
print(b)

[3 2 6 8]
